# This is a configuration file for the bacon tool
#
# Bacon repository: https://github.com/Canop/bacon
# Complete help on configuration: https://dystroy.org/bacon/config/
# You can also check bacon's own bacon.toml file
#  as an example: https://github.com/Canop/bacon/blob/main/bacon.toml

default_job = "check"

[jobs.check]
command = [
  "cargo",
  "check",
  "--all-targets",
  "--all-features",
  "--color",
  "always",
]
need_stdout = false

[jobs.clippy]
command = ["cargo", "clippy", "--all-targets", "--color", "always"]
need_stdout = false

[jobs.run]
command = [
  "cargo",
  "tauri",
  "dev",
  "--config",
  "bin/tauri-dev.conf.json",
  "--features",
  "debug",
]
need_stdout = true
allow_warnings = true
background = true
