[package]
name = "wallets"
version.workspace = true
edition.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
exclude.workspace = true
authors.workspace = true


[dependencies]
common.workspace = true
dialogs.workspace = true
crypto.workspace = true
broadcast.workspace = true

alloy.workspace = true
tauri.workspace = true
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true
secrets.workspace = true
color-eyre.workspace = true
once_cell.workspace = true
async-trait.workspace = true

enum_dispatch = "0.3.11"
coins-bip32 = "0.13"

[dev-dependencies]
rstest.workspace = true
