[package]
name = "iron"
version.workspace = true
edition.workspace = true
license-file.workspace = true
homepage.workspace = true
repository.workspace = true
exclude.workspace = true
authors.workspace = true

[dependencies]
iron-core = { workspace = true }
iron-settings = { workspace = true }
iron-networks = { workspace = true }
iron-wallets = { workspace = true }
iron-peers = { workspace = true }
iron-dialogs = { workspace = true }
iron-rpc = { workspace = true }
iron-globals = { workspace = true }
iron-ws = { workspace = true }
iron-types = { workspace = true }
iron-db = { workspace = true }
iron-sync-alchemy = { workspace = true }
tauri = { workspace = true }
tokio = { workspace = true }
thiserror = { workspace = true }
fix-path-env = { git = "https://github.com/tauri-apps/fix-path-env-rs", rev = "1a4c224" }
tauri-plugin-window-state = { git = "https://github.com/tauri-apps/plugins-workspace", branch = "v1" }
color-eyre = "0.6.2"
env_logger = "0.10.0"

[build-dependencies]
tauri-build = { version = "1.2", features = [] }

[features]
default = []
# this feature is used for production builds or when `devPath` points to the filesystem
# DO NOT REMOVE!!
custom-protocol = ["tauri/custom-protocol"]
debug = ["tauri/devtools"]
