[package]
name = "iron"
version.workspace = true
edition.workspace = true
license-file.workspace = true
homepage.workspace = true
repository.workspace = true
exclude.workspace = true
authors.workspace = true

[dependencies]
iron-forge = { workspace = true }
iron-settings = { workspace = true }
iron-networks = { workspace = true }
iron-wallets = { workspace = true }
iron-dialogs = { workspace = true }
iron-rpc = { workspace = true }
iron-ws = { workspace = true }
iron-http = { workspace = true }
iron-connections = { workspace = true }
iron-types = { workspace = true }
iron-db = { workspace = true }
iron-kv = { workspace = true }
iron-sync = { workspace = true }
iron-tracing = { workspace = true }
iron-exchange-rates = { workspace = true }
iron-broadcast = { workspace = true }
iron-simulator = { workspace = true }
iron-args = { workspace = true }
iron-token-list = { workspace = true }

serde = { workspace = true }
serde_json = { workspace = true }
tauri = { workspace = true }
tokio = { workspace = true }
thiserror = { workspace = true }
ethers = { workspace = true }
tracing = { workspace = true }

fix-path-env = { git = "https://github.com/tauri-apps/fix-path-env-rs", rev = "016512b" }
tauri-plugin-window-state = { git = "https://github.com/tauri-apps/plugins-workspace", branch = "v1" }
named-lock = "0.3.0"
auto-launch = "0.5.0"
anyhow = "1.0.79"

[build-dependencies]
tauri-build = { version = "1.2", features = [] }
iron-token-list = { workspace = true }

[features]
default = []
# this feature is used for production builds or when `devPath` points to the filesystem
# DO NOT REMOVE!!
custom-protocol = ["tauri/custom-protocol"]
debug = ["tauri/devtools"]
