[package]
name = "iron-rpc"
version.workspace = true
edition.workspace = true
license-file.workspace = true
homepage.workspace = true
repository.workspace = true
exclude.workspace = true
authors.workspace = true

[dependencies]
iron-types = { workspace = true }
iron-settings = { workspace = true }
iron-db = { workspace = true }
iron-dialogs = { workspace = true }
iron-networks = { workspace = true }
iron-wallets = { workspace = true }
iron-broadcast = { workspace = true }
iron-connections = { workspace = true }
iron-simulator = { workspace = true }

ethers = { workspace = true }
tokio = { workspace = true }
tauri = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tracing = { workspace = true }
once_cell = { workspace = true }
jsonrpc-core = { workspace = true }
async-trait = { workspace = true }
thiserror = { workspace = true }
