[package]
name = "ws"
version.workspace = true
edition.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
exclude.workspace = true
authors.workspace = true

[dependencies]
common.workspace = true
rpc.workspace = true
broadcast.workspace = true
networks.workspace = true
connections.workspace = true
args.workspace = true

tokio.workspace = true
tauri.workspace = true
serde.workspace = true
serde_json.workspace = true
once_cell.workspace = true
tracing.workspace = true
thiserror.workspace = true
url.workspace = true
futures.workspace = true
async-trait.workspace = true

tokio-tungstenite.workspace = true
