[package]
name = "iron-ws"
version.workspace = true
edition.workspace = true
license-file.workspace = true
homepage.workspace = true
repository.workspace = true
exclude.workspace = true
authors.workspace = true

[dependencies]
iron-types = { workspace = true }
iron-rpc = { workspace = true }
iron-broadcast = { workspace = true }
iron-networks = { workspace = true }
iron-connections = { workspace = true }

ethers = { workspace = true }
tokio = { workspace = true }
tauri = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
once_cell = { workspace = true }
tracing = { workspace = true }
thiserror = { workspace = true }
url = { workspace = true }
futures = { workspace = true }
async-trait = { workspace = true }

tokio-tungstenite = "0.20.1"
tungstenite = "0.20.1"
