[package]
name = "sync-anvil"
version.workspace = true
edition.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
exclude.workspace = true
authors.workspace = true

[[bin]]
name = "anvil-sync-test"
path = "src/bin/anvil-sync-test.rs"

[dependencies]
db.workspace = true
abis.workspace = true
common.workspace = true
broadcast.workspace = true
proxy-detect.workspace = true

alloy.workspace = true
tokio.workspace = true
serde_json.workspace = true
color-eyre.workspace = true
once_cell.workspace = true
tracing.workspace = true
tracing-subscriber = "0.3"
url.workspace = true
futures.workspace = true
clap.workspace = true
reqwest = { version = "0.12", features = ["json"] }

[dev-dependencies]
serial_test = "3.0"
