[package]
name = "iron-forge"
description = "Iron Wallet forge integration"
version.workspace = true
edition.workspace = true
license-file.workspace = true
homepage.workspace = true
repository.workspace = true
exclude.workspace = true
authors.workspace = true

[dependencies]
iron-types = { workspace = true }
iron-settings = { workspace = true }
iron-db = { workspace = true }
iron-networks = { workspace = true }
iron-wallets = { workspace = true }
iron-peers = { workspace = true }
iron-ws = { workspace = true }
iron-globals = { workspace = true }
iron-sync-anvil = { workspace = true }

ethers = { workspace = true }
tauri = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }
thiserror = { workspace = true }
once_cell = "1.17.1"
glob = "0.3.1"
notify = "6.0.0"
futures = "0.3.28"
regex = "1.8.1"
log = "0.4.17"
