[package]
name = "iron-forge"
description = "Iron Wallet forge integration"
version.workspace = true
edition.workspace = true
license-file.workspace = true
homepage.workspace = true
repository.workspace = true
exclude.workspace = true
authors.workspace = true

[dependencies]
iron-types = { workspace = true }
iron-settings = { workspace = true }
iron-networks = { workspace = true }
iron-broadcast = { workspace = true }

ethers = { workspace = true }
tauri = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
futures = { workspace = true }
once_cell = { workspace = true }

glob = "0.3.1"
notify = "6.0.0"
regex = "1.8.1"
