[package]
name = "ethui-forge"
description = "ethui forge integration"
version.workspace = true
edition.workspace = true
license-file.workspace = true
homepage.workspace = true
repository.workspace = true
exclude.workspace = true
authors.workspace = true

[dependencies]
ethui-types.workspace = true
ethui-settings.workspace = true
ethui-networks.workspace = true
ethui-broadcast.workspace = true
ethui-db.workspace = true

ethers.workspace = true
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true
thiserror.workspace = true
tracing.workspace = true
futures.workspace = true
once_cell.workspace = true

glob = "0.3.1"
notify = "6.0.0"
regex = "1.8.1"
