[package]
name = "iron-sync-alchemy"
version.workspace = true
edition.workspace = true
license-file.workspace = true
homepage.workspace = true
repository.workspace = true
exclude.workspace = true
authors.workspace = true

[dependencies]
iron-settings = { workspace = true }
iron-types = { workspace = true }
iron-db = { workspace = true }
iron-abis = { workspace = true }
iron-kv = { workspace = true }

ethers = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }
thiserror = { workspace = true }
once_cell = { workspace = true }
tracing = { workspace = true }
url = { workspace = true }
async-trait = { workspace = true }
futures = { workspace = true }
