[package]
name = "iron-sync-alchemy"
version.workspace = true
edition.workspace = true
license-file.workspace = true
homepage.workspace = true
repository.workspace = true
exclude.workspace = true
authors.workspace = true

[dependencies]
iron-settings = { workspace = true }
iron-types = { workspace = true }
iron-db = { workspace = true }
iron-abis = { workspace = true }
iron-sync-anvil = { workspace = true }

ethers = { workspace = true }
tauri = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }
thiserror = { workspace = true }
once_cell = { workspace = true }

url = "2.3.1"
async-trait = "0.1.68"
futures = "0.3.28"
